import { useState, useRef, useEffect } from 'react';

type Props = {
  waveHeight: number | null;
  totalHours: number;
  totalFuel: number;
};

type Message = {
  role: 'user' | 'captain';
  text: string;
  id: number;
};

export default function CaptainChat({ waveHeight, totalHours, totalFuel }: Props) {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'captain',
      text: "Welcome to the Operations Command Deck, Chief. Type your raw machinery status diagnostics or vetting queries below to generate a tactical solution path.",
      id: Date.now(),
    },
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scrolls the conversation window layout as new data tokens stream in
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  // Real-Time Asynchronous End-to-End API Webhook Dispatcher
  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
const userMessageText = input.trim();
    const userMessageId = Date.now().toString();
    // 1. Immediately inject the operator's text into the chat viewport UI layout
    setMessages((prev) => [
        ...prev,
        { role: 'user', text: userMessageText, id: userMessageId }
    ]);

    setInput('');
    setIsLoading(true);
    setStatusMessage('');

    try {
        // 2. Fire live HTTP POST packet transmission across the network tunnel wire
const response = await fetch('https://botanical-durably-coyness.ngrok-free.dev/webhook-test/95ff2840-1f0b-40d1-ad89-7a147f97dc4e'
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'ngrok-skip-browser-warning': '69420'
            },
            body: new URLSearchParams({
                machinery_context: userMessageText,
                wave_height: waveHeight || '',
                total_hours: totalHours || '',
                total_fuel: totalFuel || '',
                timestamp: new Date().toISOString(),
            }).toString()
        });

        if (!response.ok) {
            throw new Error(`HTTP network anomaly detected. Status code: ${response.status}`);
        }
      const data = await response.json();
      
      // Extract response content dynamically generated by your laptop n8n LLM pipeline engine nodes
      const captainResponse = data.text || data.output || "Technical solution request processed successfully.";
      
      // 3. Render the live AI advisory text response inside the operational chat lane
      setMessages((prev) => [
        ...prev,
        { role: 'captain', text: captainResponse, id: Date.now() }
      ]);
      
      setStatusMessage('Technical solution request queued to production webhook');

    } catch (error) {
      console.error("Critical Tunnel Transport Failure:", error);
      
      setMessages((prev) => [
        ...prev,
        { 
          role: 'captain', 
          text: "🚨 System Link Error: Unable to route your technical query down into the local laptop engine rooms. Verify your ngrok agent status terminal execution logs.", 
          id: Date.now() 
        }
      ]);
      
      setStatusMessage('Connection link transmission failed');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-[500px] w-full max-w-2xl mx-auto border border-slate-700 bg-slate-900 rounded-lg shadow-xl overflow-hidden">
      {/* Structural Top Banner Status Header */}
      <div className="bg-slate-800 border-b border-slate-700 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <div className="w-2.5 h-2.5 bg-emerald-500 rounded-full animate-pulse" />
          <h2 className="text-sm font-semibold text-slate-200 tracking-wide uppercase">
            Chief Engineer — Machinery Deck
          </h2>
        </div>
        <div className="text-xs text-slate-400 font-mono">
          Logs: Active Tunnel
        </div>
      </div>

      {/* Main Conversation Output Scroll Viewport */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0 bg-slate-950">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex w-full ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[85%] px-4 py-2.5 rounded-lg text-sm leading-relaxed shadow-sm whitespace-pre-wrap ${
                msg.role === 'user'
                  ? 'bg-blue-600 text-white rounded-br-none'
                  : 'bg-slate-800 text-slate-100 border border-slate-700 rounded-bl-none'
              }`}
            >
              <div className="font-semibold text-xs mb-1 opacity-70 tracking-wider uppercase">
                {msg.role === 'user' ? 'Chief Operator' : 'Captain Advisor'}
              </div>
              <div>{msg.text}</div>
            </div>
          </div>
        ))}
        
        {/* Animated Loading Status Node Indicator */}
        {isLoading && (
          <div className="flex w-full justify-start animate-pulse">
            <div className="bg-slate-800 border border-slate-700 text-slate-300 max-w-[85%] px-4 py-2.5 rounded-lg rounded-bl-none text-sm flex items-center space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.3s]" />
              <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce [animation-delay:-0.15s]" />
              <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" />
              <span className="text-xs pl-1 font-mono text-slate-400">Processing tactical advisory data stream...</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Action Banner Status Banner */}
      {statusMessage && (
        <div className={`px-4 py-1.5 text-center text-xs font-mono tracking-wide border-t border-b ${
          statusMessage.includes('failed') 
            ? 'bg-rose-950/40 border-rose-900 text-rose-400' 
            : 'bg-emerald-950/40 border-emerald-900 text-emerald-400'
        }`}>
          {statusMessage}
        </div>
      )}

      {/* Interface Typing Console Input Bar Form */}
      <form onSubmit={handleSendMessage} className="p-3 bg-slate-800 border-t border-slate-700 flex space-x-2">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Type Raw Machinery Symptoms or Vetting Queries Manually..."
          disabled={isLoading}
          className="flex-1 bg-slate-900 border border-slate-700 rounded px-3 py-2 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-blue-500 disabled:opacity-50"
        />
        <button
          type="submit"
          disabled={isLoading || !input.trim()}
          className="bg-slate-700 hover:bg-blue-600 disabled:bg-slate-800 text-slate-200 disabled:text-slate-500 font-medium px-4 py-2 rounded text-sm tracking-wide transition-colors duration-150 shadow focus:outline-none flex items-center justify-center min-w-[180px]"
        >
          {isLoading ? 'Processing Pipeline...' : 'Request Technical Solution'}
        </button>
      </form>
    </div>
  );
}
